In [4]:
import pandas as pd

df = pd.read_csv("data/분석1.csv")
df.rename(columns={"Unnamed: 0": "id"}, inplace=True)

# 1. 매핑용 사전 만들기

In [6]:
성과유형_list = []
성과구분_list = []
성과구분_CD_list = []

for col_nm in df.columns:
    if col_nm.startswith("성과유형"):
        성과유형_list.append(col_nm)
    elif col_nm.startswith("성과구분"):
        if col_nm.startswith("성과구분_CD"):
            성과구분_CD_list.append(col_nm)
        else:
            성과구분_list.append(col_nm)

In [7]:
성과구분_CD_list

['성과구분_CD_1',
 '성과구분_CD_2',
 '성과구분_CD_3',
 '성과구분_CD_4',
 '성과구분_CD_5',
 '성과구분_CD_6',
 '성과구분_CD_7',
 '성과구분_CD_8',
 '성과구분_CD_9',
 '성과구분_CD_10']

In [8]:
성과유형_list[:10]

['성과유형_1',
 '성과유형_2',
 '성과유형_3',
 '성과유형_4',
 '성과유형_5',
 '성과유형_6',
 '성과유형_7',
 '성과유형_8',
 '성과유형_9',
 '성과유형_10']

In [9]:
성과유형_구분_CD_dict = {key:value for key, value in zip(성과유형_list[:10], 성과구분_CD_list)}
성과유형_구분_CD_dict = {key:value for key, value in zip(성과유형_list, 성과구분_CD_list)}

In [10]:
# 짝을 맺어줌
성과유형_구분_CD_dict

{'성과유형_1': '성과구분_CD_1',
 '성과유형_2': '성과구분_CD_2',
 '성과유형_3': '성과구분_CD_3',
 '성과유형_4': '성과구분_CD_4',
 '성과유형_5': '성과구분_CD_5',
 '성과유형_6': '성과구분_CD_6',
 '성과유형_7': '성과구분_CD_7',
 '성과유형_8': '성과구분_CD_8',
 '성과유형_9': '성과구분_CD_9',
 '성과유형_10': '성과구분_CD_10'}

In [11]:
for key, value in zip(성과유형_list, 성과구분_CD_list):
    print(key, value)

성과유형_1 성과구분_CD_1
성과유형_2 성과구분_CD_2
성과유형_3 성과구분_CD_3
성과유형_4 성과구분_CD_4
성과유형_5 성과구분_CD_5
성과유형_6 성과구분_CD_6
성과유형_7 성과구분_CD_7
성과유형_8 성과구분_CD_8
성과유형_9 성과구분_CD_9
성과유형_10 성과구분_CD_10

In [12]:
type(성과유형_구분_CD_dict)

dict

In [13]:
성과유형_구분_CD_dict["성과유형_1"]

'성과구분_CD_1'

In [14]:
df

,id,성과유형_1,성과유형_2,성과유형_3,성과유형_4,성과유형_5,성과유형_6,성과유형_7,성과유형_8,성과유형_9,...,성과구분_CD_5,성과구분_CD_6,성과구분_CD_7,성과구분_CD_8,성과구분_CD_9,성과구분_CD_10,장기_합계,장기_개수,단기_합계,단기_개수
0,0,장기,단기,단기,장기,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0
1,1,단기,단기,단기,단기,단기,단기,단기,단기,단기,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,36.0,9.0
2,2,장기,단기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
3,3,단기,단기,장기,단기,단기,단기,장기,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,5.0
4,4,단기,장기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
5,5,단기,단기,장기,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0
6,6,장기,단기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
7,7,단기,단기,단기,단기,단기,장기,장기,장기,장기,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,5.0
8,8,단기,장기,단기,장기,단기,장기,단기,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,4.0
9,9,장기,장기,단기,단기,장기,단기,단기,단기,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,5.0

# 2. 계산

## 2.1. 계산

In [15]:
sum_list = []

for idx, row in df.iterrows():
    long_sum = 0
    long_cnt = 0
    short_sum = 0
    short_cnt = 0
    for key, value in row.items():
        if key in 성과유형_구분_CD_dict:
            if value == "장기":
                성과구분_value = row[성과유형_구분_CD_dict[key]]
                long_sum += 성과구분_value
                long_cnt += 1
            elif value == "단기":
                성과구분_value = row[성과유형_구분_CD_dict[key]]
                short_sum += 성과구분_value
                short_cnt += 1
    
    sum_list.append([long_sum, long_cnt, short_sum, short_cnt])

### 2.1.1. 계산 과정 참고자료

In [16]:
type(성과유형_구분_CD_dict)

dict

In [17]:
dir(성과유형_구분_CD_dict)[-10:]

['copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [18]:
type(row)

pandas.core.series.Series

In [19]:
dir(row)[-220:]

['is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs',
 '성과구분_1',
 '성과구분_10',
 '성과구분_11',
 '성과구분_12',
 '성과구분_13',
 '성과구분_14',
 '성과구분_15',
 '성과구분_16',
 '성과구분_17',
 '성과구분_18',
 '성과구분_19',
 '성과구분_2',
 '성과구분_20',
 '성과구분_21',
 '성과구분_22',
 '성과구분_23',
 '성과구분_24',
 '성과구분_25',
 '성과구분_26',
 '성과구분_27',
 '성과구분_28',
 '성과구분_29',
 '성과구분_3',
 '성과구분_30',
 '성과구분_31',
 '성과구분_32',
 '성과구분_33',
 '성과구분_34',
 '성과구분_35',
 '성과구분_36',
 '성과구분_37',
 '성과구분_38',
 '성과구분_39',
 '성과구분_4',
 '성과구분_40',
 '성과구분_41',
 '성과구분_42',
 '성과구분_43',
 '성과구분_44',
 '성과구분_45',
 '성과구분_46',
 '성과구분_47',
 '성과구분_5',
 '성과구분_6',
 '성과구분_7',
 '성과구분_8',
 '성과구분_9',
 '성과유형_1',
 '성과유형_10',
 '성과유형_11',
 '성과유형_12',
 '성과유형_13',
 '성과유형_14',
 '성과유형_15',
 '성과유형_16',
 '성과유형_17',
 '성과유형_18',
 '성과유형_19',
 '성과유형_2',
 '성과유형_20',
 '성과유형_21',
 '성과유형_22',
 '성과유형_23',
 '성과유형_24',
 '성과유형_25',
 '성과유형_26',
 '성과유형_27',
 '성과유형_28',
 '성과유형_29',
 '성과유형_3',
 '성과유형_30',
 '성과유형_31',
 '성과유형_32',
 '성과유형_33',
 '성과유형_34',
 '성과유형_35',
 '성과유형_36',
 '성과유형_37',
 '성과유형_38',
 '성과유형_39',
 '성과유형_4',
 '성과유형_40',
 '성과유형_41',
 '성과유형_42',
 '성과유형_43',
 '성과유형_44',
 '성과유형_45',
 '성과유형_46',
 '성과유형_47',
 '성과유형_48',
 '성과유형_49',
 '성과유형_5',
 '성과유형_50',
 '성과유형_51',
 '성과유형_52',
 '성과유형_6',
 '성과유형_7',
 '성과유형_8',
 '성과유형_9']

In [20]:
# for key, value in row.items():
#     print(key, value)

In [21]:
idx

9

In [22]:
row

id              9
성과유형_1         장기
성과유형_2         장기
성과유형_3         단기
성과유형_4         단기
             ...
성과구분_CD_10    NaN
장기_합계         NaN
장기_개수         3.0
단기_합계         NaN
단기_개수         5.0
Name: 9, Length: 119, dtype: object

In [23]:
row["성과유형_1"]

'장기'

In [24]:
성과유형_구분_CD_dict["성과유형_1"]

'성과구분_CD_1'

In [25]:
row["성과구분_CD_1"]

nan

## 2.2. 체크

In [26]:
df[성과유형_list[:10] + 성과구분_CD_list].iloc[:2]

,성과유형_1,성과유형_2,성과유형_3,성과유형_4,성과유형_5,성과유형_6,성과유형_7,성과유형_8,성과유형_9,성과유형_10,성과구분_CD_1,성과구분_CD_2,성과구분_CD_3,성과구분_CD_4,성과구분_CD_5,성과구분_CD_6,성과구분_CD_7,성과구분_CD_8,성과구분_CD_9,성과구분_CD_10
0,장기,단기,단기,장기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,단기,단기,단기,단기,단기,단기,단기,단기,단기,장기,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

In [27]:
sum_list[:2]

[[nan, 2, nan, 2], [4.0, 1, 36.0, 9]]

# 3. DataFrame에 추가

In [28]:
add_col_list = ["장기_합계", "장기_개수", "단기_합계", "단기_개수"]
df[add_col_list] = sum_list

In [29]:
df

,id,성과유형_1,성과유형_2,성과유형_3,성과유형_4,성과유형_5,성과유형_6,성과유형_7,성과유형_8,성과유형_9,...,성과구분_CD_5,성과구분_CD_6,성과구분_CD_7,성과구분_CD_8,성과구분_CD_9,성과구분_CD_10,장기_합계,장기_개수,단기_합계,단기_개수
0,0,장기,단기,단기,장기,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0
1,1,단기,단기,단기,단기,단기,단기,단기,단기,단기,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,36.0,9.0
2,2,장기,단기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
3,3,단기,단기,장기,단기,단기,단기,장기,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,5.0
4,4,단기,장기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
5,5,단기,단기,장기,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0
6,6,장기,단기,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
7,7,단기,단기,단기,단기,단기,장기,장기,장기,장기,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,5.0
8,8,단기,장기,단기,장기,단기,장기,단기,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,4.0
9,9,장기,장기,단기,단기,장기,단기,단기,단기,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,5.0

In [30]:
df.to_csv("data/분석1_장단기_합계_개수_추가.csv", index=False)